apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jenkins
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: Authorization, origin, accept
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, OPTIONS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
spec:
  ingressClassName: nginx
  rules:
  - host: devopslaboratorio.com
    http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 80

      # # - path: /artifactory
      # #   pathType: Prefix
      # #   backend:
      # #     service:
      # #       name: artifactory-oss
      # #       port:
      # #         number: 8081

      # # - path: /
      # #   pathType: Prefix
      # #   backend:
      # #     service:
      # #       name: artifactory-oss
      # #       port:
      # #         number: 8082

      # - path: /prometheus
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: my-prometheus-server
      #       port:
      #         number: 80

      # - path: /sonarqube
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: sonarqube-sonarqube
      #       port:
      #         number: 9000

      # # Ruta dinámica para el microservicio CSV
      # - path: /api/v1/data/reporteGithub.csv
      #   pathType: ImplementationSpecific
      #   backend:
      #     service:
      #       name: csv-microservice
      #       port:
      #         number: 5000
      # - path: /api/v1/data/reporteFortify.csv
      #   pathType: ImplementationSpecific
      #   backend:
      #     service:
      #       name: csv-microservice
      #       port:
      #         number: 5000
      # - path: /pgadmin4
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: svc-pgadmin
      #       port:
      #         number: 5052
    
