apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  labels:
    app: jenkins
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: jenkins
